[book]
authors = ["Leah Gibson"]
language = "en"
multilingual = false
src = "src"
title = "Leah Gibson"
[preprocessor.index]
[preprocessor.links]
[build]
build-dir = "docs"
create-missing = true
[output.html]
mathjax-support = true
